-- Crear la tabla de Roles
CREATE TABLE Rol (
  IdRol NUMBER,
  NombreRol VARCHAR2(50),
  PRIMARY KEY (IdRol)
);

-- Crear la tabla de Usuarios
CREATE TABLE Usuario (
  IdUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
  Nombres VARCHAR2(100),
  Apellidos VARCHAR2(100),
  NombreUsuario VARCHAR2(100),
  Contraseña VARCHAR2(255),
  IdRol NUMBER,
  Activo NUMBER(1),
  PRIMARY KEY (IdUsuario),
  CONSTRAINT fk_rol FOREIGN KEY (IdRol) REFERENCES Rol(IdRol)
);

-- Crear la tabla de Especialidades
CREATE TABLE Especialidad (
  IdEspecialidad NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NombreEspecialidad VARCHAR2(100),
  PRIMARY KEY (IdEspecialidad)
);

-- Crear la tabla de Pacientes
CREATE TABLE Paciente (
  IdPaciente NUMBER GENERATED BY DEFAULT AS IDENTITY,
  Nombre VARCHAR2(100),
  Apellido VARCHAR2(100),
  Direccion VARCHAR2(255),
  Telefono VARCHAR2(20),
  FechaNacimiento DATE,
  Cedula VARCHAR2(20),
  IdUsuario NUMBER,
  PRIMARY KEY (IdPaciente),
  CONSTRAINT fk_paciente_usuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario)
);

-- Crear la tabla de Doctores
CREATE TABLE Doctor (
  IdDoctor NUMBER GENERATED BY DEFAULT AS IDENTITY,
  Nombre VARCHAR2(100),
  Telefono VARCHAR2(20),
  IdEspecialidad NUMBER,
  Cedula VARCHAR2(20),
  IdUsuario NUMBER,
  PRIMARY KEY (IdDoctor),
  CONSTRAINT fk_doctor_especialidad FOREIGN KEY (IdEspecialidad) REFERENCES Especialidad(IdEspecialidad),
  CONSTRAINT fk_doctor_usuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario)
);

-- Crear la tabla de Horarios
CREATE TABLE Horario (
  IdHorario NUMBER GENERATED BY DEFAULT AS IDENTITY,
  IdDoctor NUMBER,
  DiaSemana VARCHAR2(10),
  HoraInicio INTERVAL DAY TO SECOND,
  HoraFin INTERVAL DAY TO SECOND,
  PRIMARY KEY (IdHorario),
  CONSTRAINT fk_horario_doctor FOREIGN KEY (IdDoctor) REFERENCES Doctor(IdDoctor)
);

-- Crear la tabla de Citas
CREATE TABLE Cita (
  IdCita NUMBER GENERATED BY DEFAULT AS IDENTITY,
  FechaCita DATE,
  HoraCita INTERVAL DAY TO SECOND,
  IdPaciente NUMBER,
  IdDoctor NUMBER,
  Estado VARCHAR2(20),
  PRIMARY KEY (IdCita),
  CONSTRAINT fk_cita_paciente FOREIGN KEY (IdPaciente) REFERENCES Paciente(IdPaciente),
  CONSTRAINT fk_cita_doctor FOREIGN KEY (IdDoctor) REFERENCES Doctor(IdDoctor)
);

-- Crear la tabla de Historias Clínicas
CREATE TABLE HistoriaClinica (
  IdHistoriaClinica NUMBER GENERATED BY DEFAULT AS IDENTITY,
  IdPaciente NUMBER,
  IdDoctor NUMBER,
  FechaCreacion DATE,
  Diagnostico VARCHAR2(255),
  Tratamiento VARCHAR2(255),
  NotasAdicionales VARCHAR2(255),
  IdCita NUMBER,
  PRIMARY KEY (IdHistoriaClinica),
  CONSTRAINT fk_historia_paciente FOREIGN KEY (IdPaciente) REFERENCES Paciente(IdPaciente),
  CONSTRAINT fk_historia_doctor FOREIGN KEY (IdDoctor) REFERENCES Doctor(IdDoctor),
  CONSTRAINT fk_historia_cita FOREIGN KEY (IdCita) REFERENCES Cita(IdCita)
);


INSERT INTO ROL(IDROL,NOMBREROL) VALUES (1,'admin');
INSERT INTO ROL(IDROL,NOMBREROL) VALUES (21,'paciente');
INSERT INTO ROL(IDROL,NOMBREROL) VALUES (2,'doctor');
--*IDUSUARIO

INSERT INTO USUARIO (NOMBRES,APELLIDOS,NOMBREUSUARIO,CONTRASEÑA,IDROL,activo) VALUES ('admin',' ','admin','admin',1,1);


